### ISSUE TITLE
Having issues writing a "Note" column with various encodings

### ISSUE THREAD

**Issue by schwallie2** [maybelinot/df2gspread#19]
The specific sentence the upload stops working on is here:

> u'Love what you do to help the most kindest souls on the planet!!\x1a\x1a Thank you so so much!!!!'

What happens is basically the grouped object (This is row 1100 / 7000) shows it as writing, and the cells object ( `wks.update_cells(list(cells))` ) looks totally fine, but it just doesn't write correctly to the Google doc. The ~20 or so rows in the group end up being blank, with the index written previous still being there.

I've tried using:
`d['Note'] = d['Note'].str.decode('utf8')`

Along with encoding to utf8. Encoding to ascii/others doesn't work on the series as I get errors.

Is there a specific encoding I should be using, or some kind of safe method to get this to write?

**Comment by maybelinot** [comment]
@schwallie2 I think [this](http://stackoverflow.com/a/32382864/5163960) could help you.

**Comment by schwallie2** [comment]
@maybelinot Saw that but was hoping for a more vectorized approach, and in terms of df2gspread I think it should at least be warning if the rows are not going to show up in Google Spreadsheets due to encoding issues, right?

**Comment by maybelinot** [comment]
@schwallie2 The problem is on google side and I think that warning should came from [gspread](https://github.com/burnash/gspread) package because all API calls happens there.. It's too expensive to check if uploaded data is identical with original one.. But I think there could be added some flag, like `verify_downloading` or something like that..

**Comment by schwallie2** [comment]
Ok we can move it to them. I just did an .apply() with the strip_unprintable in the meantime!
