### ISSUE TITLE
Clarification on authentication process

### ISSUE THREAD

**Issue by AschHarwood** [maybelinot/df2gspread#20]
My goal is to upload a pandas dataframe to google sheets. I've been struggling with authentication.

My code is:
```

spreadsheet = '/Users/aschharwood/Google_Drive/gspread/acled_5.gsheet'
wks_name = "Sheet1"

d2g.upload(df, spreadsheet, wks_name)
```

The first error I got was:

```
`---------------------------------------------------------------------------
InvalidClientSecretsError                 Traceback (most recent call last)
<ipython-input-33-85103973c811> in <module>()
----> 1 d2g.upload(df, spreadsheet, wks_name)

/Users/aschharwood/anaconda2/lib/python2.7/site-packages/df2gspread/df2gspread.pyc in upload(df, gfile, wks_name, chunk_size, col_names, row_names, clean, credentials, start_cell, df_size, new_sheet_dimensions)
     74     '''
     75     # access credentials
---> 76     credentials = get_credentials(credentials)
     77     # auth for gspread
     78     gc = gspread.authorize(credentials)

/Users/aschharwood/anaconda2/lib/python2.7/site-packages/df2gspread/utils.pyc in get_credentials(credentials, client_secret_file, refresh_token)
     81 
     82         flow = client.flow_from_clientsecrets(
---> 83             client_secret_file, SCOPES)
     84         flow.redirect_uri = client.OOB_CALLBACK_URN
     85         if flags:

/Users/aschharwood/anaconda2/lib/python2.7/site-packages/oauth2client/util.pyc in positional_wrapper(*args, **kwargs)
    135                 elif positional_parameters_enforcement == POSITIONAL_WARNING:
    136                     logger.warning(message)
--> 137             return wrapped(*args, **kwargs)
    138         return positional_wrapper
    139 

/Users/aschharwood/anaconda2/lib/python2.7/site-packages/oauth2client/client.pyc in flow_from_clientsecrets(filename, scope, redirect_uri, message, cache, login_hint, device_uri)
   2103     try:
   2104         client_type, client_info = clientsecrets.loadfile(filename,
-> 2105                                                           cache=cache)
   2106         if client_type in (clientsecrets.TYPE_WEB,
   2107                            clientsecrets.TYPE_INSTALLED):

/Users/aschharwood/anaconda2/lib/python2.7/site-packages/oauth2client/clientsecrets.pyc in loadfile(filename, cache)
    164 
    165     if not cache:
--> 166         return _loadfile(filename)
    167 
    168     obj = cache.get(filename, namespace=_SECRET_NAMESPACE)

/Users/aschharwood/anaconda2/lib/python2.7/site-packages/oauth2client/clientsecrets.pyc in _loadfile(filename)
    124     except IOError as exc:
    125         raise InvalidClientSecretsError('Error opening file', exc.filename,
--> 126                                         exc.strerror, exc.errno)
    127     return _validate_clientsecrets(obj)
    128 

InvalidClientSecretsError: ('Error opening file', '/Users/aschharwood/.gdrive_private', 'No such file or directory', 2)
```
`

When I did create the directory, I got an error that said .gdrive_private IS a directory. I've also tried renaming the file and putting it in my working directory.

Can you please clarify where exactly i should store the client_secrets file for authorization?

Thanks!

**Comment by maybelinot** [comment]
@AschHarwood As said in exception above you should store the file as `/Users/aschharwood/.gdrive_private`, it means in folder `/Users/aschharwood` with name `.gdrive_private` without extension.

**Comment by AschHarwood** [comment]
This worked perfectly. Thank you so much for the clarification!

**Comment by tdonald6040** [comment]
is there anyway you can clarify even further, I've tried your fix but I keep getting the same error. what EXACTLY do I need write? Can you provide a sample of what the initial 3 lines of code should look like? Thanks.

**Comment by maybelinot** [comment]
>  what EXACTLY do I need write?

What exactly do you need to write where?
You just need to get file with credentials from Google Developer console(following [this README block](https://github.com/maybelinot/df2gspread#access-credentials)) and store it in your home directory with name `.gdrive_private`

**Comment by RajYadav7121** [comment]
Hi, I have downloaded the file and named it as .gdrive_private in path C:\Users\RAJ, so the actual path of my cred file is C:\Users\RAJ\.gdrive_private, still getting this "oauth2client.clientsecrets.InvalidClientSecretsError: ('Error opening file', 'C:\\Users\\RAJ\\.gdrive_private', 'No such file or directory', 2)" error message. Please help regarding this.

**Comment by maybelinot** [comment]
Hi @RajYadav7121, the path should be exactly as in the error exception, 
> Hi, I have downloaded the file and named it as .gdrive_private in path C:\Users\RAJ, so the actual path of my cred file is C:\Users\RAJ.gdrive_private, still getting this

The actual path should be `C:\Users\RAJ\.gdrive_private`

**Comment by lpmbgithub** [comment]
> Hi @RajYadav7121, the path should be exactly as in the error exception,
> 
> > Hi, I have downloaded the file and named it as .gdrive_private in path C:\Users\RAJ, so the actual path of my cred file is C:\Users\RAJ.gdrive_private, still getting this
> 
> The actual path should be `C:\Users\RAJ\.gdrive_private`

Could you please explain WHY the file has to be exactly there?  Is there simply no way to specify WHERE the file could be, apart from this location?   For instance --- what if I have two or 3 applications on the run for different google apps domains --- the keys wouldn't work across each domain.
