### ISSUE TITLE
Cache mechanism

### ISSUE THREAD

**Issue by hadim** [maybelinot/df2gspread#23]
This lib is super useful ! Thanks for that.

What do you think of a cache mechanism that will store the df as an .h5 file in a standard path such as `$HOME/.df2gspread` or similar ?

**Comment by maybelinot** [comment]
Hey @hadim,
I'm glad to here that you've found this library useful!

Regarding the caching I'm not sure that fully understood your concerns. Why do you think this feature would be useful? I mean there is a lot of way to store your `df`s after downloading. And the main goal of this library is to create a layer between pandas and gspread. 
I think it would be much easier for any user to import another library which allows caching (like this one https://github.com/moble/h5py_cache). If I got your idea in wrong way can you please write some examples of how you imagine this to work?=)

**Comment by hadim** [comment]
Sorry, I should have explained my use case better.

Caching could be useful to avoid web requests when developing a script. That would be only one option to `g2d.download()`. Something like that `g2d.download(spreadsheet, x, col_names=True, row_names=True, cache=True)`

Of course, default would be to disable caching.

Now if you think it's too much off topic for your library I perfectly understand.

**Comment by maybelinot** [comment]
Thanks for explanation,
Personally I see this as a rarely used case. As I'm expecting this library to be used in general is to update the data (locally or on the Google side). Continuous downloading is not the common use case so I don't really want to overload the library with this code for now.

I think you can easily simulate the caching by creation of alias for `gspread2df` with caching decorator for the time you developing the script. 
If there will be more interest in this feature I'm ok to review this issue again..
