### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Ostinchuk** [maybelinot/df2gspread#24]
Hi!

I'm facing a problem. There is an error which I cannot fix: 
InvalidClientSecretsError: ('Error opening file', 'C:\\Users\\***/.gdrive_private', 'Permission denied', 13)

I opened an access for all for this folder but it does not help.
Any ideas how to fix it?

**Comment by maybelinot** [comment]
Hi @Ostinchuk,

Try to look for an answer in [this thread](https://stackoverflow.com/questions/13215716/ioerror-errno-13-permission-denied-when-trying-to-open-hidden-file-in-w-mod).

Don't think that [df2gspread ](https://github.com/maybelinot/df2gspread) or [oauth2client](https://github.com/google/oauth2client) has something to do with this issue..
