### ISSUE TITLE
Authentication on headless server

### ISSUE THREAD

**Issue by jat255** [maybelinot/df2gspread#25]
I'm trying to run some code using df2gspread on a headless server (using Xvfb), and running into a challenge for the authentication, since I cannot open a browser to authorize my application.

The code suggests: 
```
If your browser is on a different machine then exit and re-run this
application with the command-line parameter

  --noauth_local_webserver
```

but I'm not sure how I would specify that parameter from my df2gspread code. Any suggestions/alternatives?

**Comment by jat255** [comment]
Follow-up: I was able to copy the `drive.json` file from my local testing machine, and it accepted that. Not sure if that's the right way to do things, but it seems to be working...

**Comment by maybelinot** [comment]
@jat255 that's the right way atm

`--noauth_local_webserver` option came from google oauth library and I think I'm not handling this in df2gspread. Will look how to deal with this later.

**Comment by nbarraille** [comment]
In case someone is reading this today, here is my (extremely hacky) solution: When both ports 8080 and 8090 are not available, it automatically falls back to headless auth...

```python
nc8080 = subprocess.Popen(["nc", "-l", "-p", "8080"])
nc8090 = subprocess.Popen(["nc", "-l", "-p", "8090"])
try:
    return df2gspread.get_credentials()
finally:
    nc8080.kill()
    nc8090.kill()
```
