### ISSUE TITLE
Updating data is slow

### ISSUE THREAD

**Issue by spiantino** [maybelinot/df2gspread#26]
Looks like it can take up to a few minutes for each call to df2gspread.upload. Any reason that might be inefficient, or using an older version of the API? For a longer script that updates a few thousand cells it can take up to 10 minutes

**Comment by maybelinot** [comment]
Have you tried to play with chunk size? Personally I haven't seen any issues like that, cause never really use it to upload huge files, will look how it performs with large data

**Comment by maybelinot** [comment]
Upgraded to Google API v4, shouldn't be so slow not
