### ISSUE TITLE
Release to conda-forge

### ISSUE THREAD

**Issue by hadim** [maybelinot/df2gspread#28]
Would you be interested to release your package to [conda-forge](https://conda-forge.org/) ? This is widely used in the Python scientific community.

I can help with that if needed.

**Comment by maybelinot** [comment]
Isn't it yet? 
https://github.com/conda-forge/df2gspread-feedstock
I'm quite sure that I did nothing for that, though :D

**Comment by hadim** [comment]
My bad :-)

Yeah, it's common for people to create a feedstock even if they are not the original author.

(Super useful library by the way)
