### ISSUE TITLE
gspread authentication on df2gspread

### ISSUE THREAD

**Issue by soad1982** [maybelinot/df2gspread#29]
Hi,

I'm trying to upload to drive using an already authenticated session with gspread:

    scope = ['https://spreadsheets.google.com/feeds']
    creds = ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope)
    client = gspread.authorize(creds)

I can add rows just fine, which is awesome BTW.
    sheet = client.open("file_name")
    worksheet = sheet.worksheet(sheet_name)
   row = something. ..
   worksheet.append_row(row)

Now I'm trying to use pandas, with something like this:

  df = pd.read_csv(file_name)
  d2g.upload(df, sheet, worksheet)

But I got file no exists errors, is possible to reuse the auth already working?

I tried to copy my client_secret.json to ~/.gdrive_private and ~/.oauth/drive.json as I'm not sure which is the correct one and seems to be asking for both, anyway I only have one file client_secret.json and I got this error:  File "/usr/local/lib/python2.7/site-packages/oauth2client/client.py", line 302, in new_from_json
    module_name = data['_module']
KeyError: '_module'

Thanks!

**Comment by maybelinot** [comment]
Hi @soad1982 

You can provide credentials directly, when you're calling `d2g.upload` [here](https://github.com/maybelinot/df2gspread/blob/master/df2gspread/df2gspread.py#L59)

With regard to credentials file: you have to provide only `~/.gdrive_private`, and `~/.oauth/drive.json` will be created automatically when you'll be asked for permissions.

Hope that helps!
