### ISSUE TITLE
Update df2gspread to use gspread >= 2.0 in order to speed up insertions

### ISSUE THREAD

**Issue by jasonqng** [maybelinot/df2gspread#31]
@maybelinot Looks like gspread was updated last month to use the new Google Sheet API v4, which is lightning fast compared to the API gspread in the version we depend on uses: https://github.com/burnash/gspread/releases/tag/v2.0.0. Likely breaking changes that we'll have to resolve, but it'll solve or mitigate issues like https://github.com/maybelinot/df2gspread/issues/30 and https://github.com/maybelinot/df2gspread/issues/26, which I can confirm that I have as well when I try to upload large dataframes to sheets.

**Comment by maybelinot** [comment]
@jasonqng Yes, you're right, I was looking into that few days ago, but had no time to work on the update. I'll appreciate if you'll have time to spend on this, otherwise I'll start migration process in a couple of weeks.

**Comment by maybelinot** [comment]
Upgraded to Google API v4.
