### ISSUE TITLE
Gsheets API v4 429 Error

### ISSUE THREAD

**Issue by redpoint13** [maybelinot/df2gspread#34]
I'm attempting to load a dataframe to a gsheet with code that has previously worked.  The Google API is responding with an error code 429.  Here is the full error:
```
APIError: {
  "error": {
    "code": 429,
    "message": "Insufficient tokens for quota 'ReadGroup' and limit 'USER-100s' of service 'sheets.googleapis.com' for consumer 'project_number:REMOVED.",
    "status": "RESOURCE_EXHAUSTED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developer console API key",
            "url": "https://console.developers.google.com/project/REMOVED/apiui/credential"
          }
```

Researching the error here (https://developers.google.com/analytics/devguides/reporting/core/v4/errors) , the error appears to suggest the fix is to "Retry using exponential back-off. You need to slow down the rate at which you are sending the requests."  

It's not apparent in the documentation of df2spread, if or how this can be accomplished.   

Here is the command being sent (tmp is a pandas dataframe):

```
d2g.upload(tmp, spreadsheet, accel, credentials=credentials,
                   row_names=False, df_size=True, new_sheet_dimensions=(tmp.shape))
```

**Comment by maybelinot** [comment]
Hi @redpoint13 

From my experience this could happen when you're calling `d2g` too often and running out of quota limits (with Google API v4 that's too easy).

You can look at google developer console to see how many requests you've made. 
As a solution you can use `time.sleep` to slow down amount of requests sent to Google API per minute. Or use some of python backoff libraries (like [this](https://github.com/litl/backoff) one)

In general `df2gspread` makes 1 to 3 requests per `upload` (additional 2 for columns and rows if they're sent)

**Comment by maybelinot** [comment]
I close the issue, let me know if I can help you with anything else!
