### ISSUE TITLE
Number Format Columns of Pandas Dataframes are uploaded as Texts in Google Sheets

### ISSUE THREAD

**Issue by outlier89** [maybelinot/df2gspread#37]
Since my project deals exclusively with numbers, it would be a great help to me if the number formats in dataframe are uploaded in number formats only.

**Comment by amodig** [comment]
Yeah, spreadsheets usually deal a lot with numbers... It's possible to write a [formatting JSON recipe](https://developers.google.com/sheets/api/samples/formatting) with the help of [gspread](https://github.com/burnash/gspread), but it's a bit annoying extra step.

**Comment by maybelinot** [comment]
I think the easiest solution at the moment would be to apply custom formatting to a spreadsheet after the data were uploaded, or as @amodig suggested use gspread. Right now I don't have in plans to include this functionality, as I personally don't use spreadsheets for analytics.

**Comment by nelsonauner** [comment]
@maybelinot if I wrote a PR that did this, would you consider including it in your package?

**Comment by maybelinot** [comment]
@nelsonauner Sure, feel free to submit it!
