### ISSUE TITLE
AttributeError: 'Worksheet' object has no attribute 'get_int_addr'

### ISSUE THREAD

**Issue by G-Simeone** [maybelinot/df2gspread#38]
Hi, I have used this package wonderfully but when I was testing my application on a new computer I incurred into the error above. 

To test I created a new environment called `Transparency_Italy_TRAC` using miniconda and installed df2gspread using `conda install -c conda-forge df2gspread`. When running `python app.py` I get the following full error:

> Traceback (most recent call last):  File "app.py", line 138, in <module> d2g.upload(value, SPREADSHEET_ID, key, credentials=credentials, row_names=True)
 File "/home/gabriele/anaconda3/envs/Transparency_Italy_TRAC/lib/python3.6/site-
 packages/df2gspread/df2gspread.py", line 101, in upload
 start_row_int, start_col_int = wks.get_int_addr(start_cell)
 AttributeError: 'Worksheet' object has no attribute 'get_int_addr'

So I went to check in `"/home/gabriele/anaconda3/envs/Transparency_Italy_TRAC/lib/python3.6/site-
 packages/df2gspread/df2gspread.py`

The thing is that when running app.py in the Anaconda3 base environment where I had installed df2gspread - there was no problem. So I went to source code of the package in both environments and actually found that in the one in the environment I created to test the project the files were last updated in 2016 - while in the package of the one downloaded in Anaconda3 some files of the library were updated in 2018. 

The `conda install -c conda-forge df2gspread` seems to be installing an older version - any idea how to solve this?

**Comment by maybelinot** [comment]
Hi @G-Simeone, conda-forge package wasn't created or supported by me, I think [that](https://github.com/conda-forge/df2gspread-feedstock)'s the place where it lives and as far as I can tell this is the latest version.

What's the package version you installed via conda?

**Comment by G-Simeone** [comment]
Hey @maybelinot! It's the df2gspread-0.2.3 that gets installed with conda. I will post this in the conda-forge package, but i just tried creating a new virtual environment using virtualenv + pip and it works smoothly again...

**Comment by maybelinot** [comment]
Greta, good to hear!
