### ISSUE TITLE
pycrypto is dead, raises problems on Windows.  

### ISSUE THREAD

**Issue by gsime1** [maybelinot/df2gspread#39]
Hi, sorry to create a second issue, but I am incurring in a dead end. I am testing the app i created using this amazing library on a Windows, and unfortunately one of the core dependencies that I see in `setup.py` is not being updated anymore, and on Windows, using the Visual Studio Community edition compiler this raises all sorts of errors. Would it be possible to switch to [PyCryptodome](https://github.com/dlitz/pycrypto/issues/238) instead?

**Comment by maybelinot** [comment]
Hi @gsime1 I don't even see `import pycrypto`  anywhere in the project, I'll test this on Windows and remove..

**Comment by gsime1** [comment]
Hi! I think it is in setup.py at line 36?
