### ISSUE TITLE
exit silently if no raw_data

### ISSUE THREAD

**Issue by gregroberts** [maybelinot/df2gspread#42]
https://github.com/maybelinot/df2gspread/blob/01bc46d267c8ea42098f425758930bb28cab0573/df2gspread/gspread2df.py#L84-L85

Exiting silently when raw_data is empty seems like unreasonable behaviour.

This should either return an empty dataframe, or raise `pandas.errors.EmptyDataError`.

Context: I use this library with Luigi as part of an ETL workflow. When raw_data is empty, the whole thing exits without giving any signal as to why.

Happy to draw up a PR if you'd prefer.

**Comment by maybelinot** [comment]
Good catch, yes, I'd appreciate a PR. Thanks @gregroberts
