### ISSUE TITLE
oauth2client.clientsecrets.InvalidClientSecretsError: ('Error opening file',.......) in df2gpread

### ISSUE THREAD

**Issue by RajYadav7121** [maybelinot/df2gspread#46]
Hi i am trying to upload my sample dataframe to my google sheet using df2gpread which i also tried with gspread-pandas but the problem i am facing is storing the google credentials file at right place in both the case. for eg:

from df2gspread import df2gspread as d2g
import pandas as pd

d = [pd.Series([1., 2., 3.], index=['a', 'b', 'c']),
    pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])]
df = pd.DataFrame(d)
print(df)

spreadsheet = '1DxR8u57A8ASMJ4re_4coheYz0Q2xgMlb-4_5lDjy3w8'
wks_name = 'Sheet2'
d2g.upload(df, spreadsheet, wks_name)

This is my actual code and following is the error i keep on getting:
oauth2client.clientsecrets.InvalidClientSecretsError: ('Error opening file', 'C:\\Users\\RAJ\\.gdrive_private', 'No such file or directory', 2)

The credentials file is stored in "C:\\Users\\RAJ" this path and filename is .gdrive_private still getting that error. Please help

**Comment by maybelinot** [comment]
Replied in another issue, try to change permissions for the file if you are sure that it's in the right place, even though for windows it shouldn't be a problem
