### ISSUE TITLE
Possible to unpin google-api-python-client version?

### ISSUE THREAD

**Issue by riordan** [maybelinot/df2gspread#49]
Hi there! I'm a big fan of df2gspread. Unfortunately the hard dependency pin of `google-api-python-client==1.6.7` means that it's incompatible with several Google libraries we use (such as tfx, which uses `>=1.7.8`).

I'm hoping that a ranged dependency here might enable some broader library compatibility.

**Comment by maybelinot** [comment]
hi @riordan, let me bump the version

**Comment by riordan** [comment]
Thank you!

**Comment by jmarrec** [comment]
@maybelinot Thanks for the useful module and addressing this issue. Are you planning on a new release on pypi soon? 

Nothing pressing, in the meantime I'll pip upgrade from git anyways, but I don't want to forget to revert to official (`pip install --upgrade git+https://github.com/maybelinot/df2gspread.git`)

**Comment by moeslami** [comment]
@maybelinot , could you please publish a new version on pypi with this change to unpin google-api-python-client?

**Comment by skuldy** [comment]
Asking again if there'll be a new release on pypi soon with the relaxed pinning?
