### ISSUE TITLE
"Installed application" option no more available from Google Developer Console?

### ISSUE THREAD

**Issue by spex66** [maybelinot/df2gspread#5]
Thank you for sharing this llibrary, as promised I'm testing the basics ASAP :)

## dependencies
I installed this dependencies on top of my Anaconda Python 2.7 dist (you may want to add this to your readme? Are there more dependencies?):
```
pip install gspread
pip install --upgrade google-api-python-client
```
The latter one installed:
```
Successfully installed 
google-api-python-client-1.4.2 
oauth2client-1.5.1 
simplejson-3.8.0 
uritemplate-0.6
```
FIrst question: Are this the same versions you are working with?

## oauth2 id creation problems
Tried to follow your detailed steps how to create a ClientId for "Installed application".
All your steps fit the Google documentation I found here:
* https://developers.google.com/drive/web/quickstart/python
* https://developers.google.com/api-client-library/python/auth/installed-app

But I'm not able to find the "Installed application" option in this step:
![image](https://cloud.githubusercontent.com/assets/1098323/10216792/e271c3fe-682b-11e5-8334-27e3d5f33870.png)

Is it still available for you?
Or was there a change, which is not reflected yet in Google docs?

## ```oauth2client.file``` module problems

In parallel I've tested the basic steps in an interactive IPython session, and stumbled over this problem:

```
In [1]: import oauth2client, os
In [2]: CLIENT_SECRET_FILE = os.path.expanduser('~/.gdrive_private')
In [3]: DEFAULT_TOKEN = os.path.expanduser('~/.oauth/drive.json')
In [4]: store = oauth2client.file.Storage(DEFAULT_TOKEN)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-28c0bcf4ba8d> in <module>()
----> 1 store = oauth2client.file.Storage(DEFAULT_TOKEN)

AttributeError: 'module' object has no attribute 'file'
```

This irritates me, because "file.py" is in the lib and can be imported like this:
```
In [5]: from oauth2client import file
In [6]: oauth2client.file
Out[6]: <module 'oauth2client.file' from 'C:\Anaconda230-64bit\lib\site-packages\oauth2client\file.pyc'>
```

## next steps
Would be great, if we can figure out this basics together.
I'm really interested in the Google Drive / Pandas integration, but struggled with the OAuth2 4 months ago... and now it is blocking me again.

**Comment by spex66** [comment]
OK, first results:
## oauth2 id creation problems
It is the "Other" option, which ends up with a ```CLIENT_SECRET_FILE``` with this structure:
```
{
	"installed": {
		"client_id": "**********.apps.googleusercontent.com",
		"auth_uri": "https://accounts.google.com/o/oauth2/auth",
		"token_uri": "https://accounts.google.com/o/oauth2/token",
		"auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
		"client_secret": "*********",
		"redirect_uris": ["urn:ietf:wg:oauth:2.0:oob", "http://localhost"]
	}
}
```

## oauth2client.file module problems
Solution for now is to import the submodules before using them:
```
import oauth2client 
from oauth2client import tools
from oauth2client import file

# with the imports above this dot notation works
oauth2client.tools.argparser
store = oauth2client.file.Storage(DEFAULT_TOKEN)
```

## next issue
Maybe because it is Windows, I'm running now into an SSL problem.
I debugged it step by step

The ```gfile_id = get_file_id(credentials, gfile)``` (gspread2df.py:44) went fine and I got the correct id for a sheetname, so authentication seems to work.

The error occurs with the ```spsh = gc.open_by_key(gfile_id)``` in (gfiles.py:68)
Traceback in all its beauty:
```
---------------------------------------------------------------------------
SSLError                                  Traceback (most recent call last)
<ipython-input-15-678cf23c5a31> in <module>()
----> 1 spsh = gc.open_by_key(gfile_id)

C:\arwa\Anaconda230-64bit\lib\site-packages\gspread\client.pyc in open_by_key(self, key)
    163
    164         """
--> 165         feed = self.get_spreadsheets_feed()
    166         for elem in feed.findall(_ns('entry')):
    167             alter_link = finditem(lambda x: x.get('rel') == 'alternate',

C:\arwa\Anaconda230-64bit\lib\site-packages\gspread\client.pyc in get_spreadsheets_feed(self, visibility, projection)
    227                             visibility=visibility, projection=projection)
    228
--> 229         r = self.session.get(url)
    230         return ElementTree.fromstring(r.read())
    231

C:\arwa\Anaconda230-64bit\lib\site-packages\gspread\httpsession.pyc in get(self, url, **kwargs)
     77
     78     def get(self, url, **kwargs):
---> 79         return self.request('GET', url, **kwargs)
     80
     81     def delete(self, url, **kwargs):

C:\arwa\Anaconda230-64bit\lib\site-packages\gspread\httpsession.pyc in request(self, method, url, data, headers)
     69
     70         self.connections[
---> 71             uri.scheme + uri.netloc].request(method, url, data, headers=request_headers)
     72         response = self.connections[uri.scheme + uri.netloc].getresponse()
     73

C:\arwa\Anaconda230-64bit\lib\httplib.pyc in request(self, method, url, body, headers)
   1051     def request(self, method, url, body=None, headers={}):
   1052         """Send a complete request to the server."""
-> 1053         self._send_request(method, url, body, headers)
   1054
   1055     def _set_content_length(self, body, method):

C:\arwa\Anaconda230-64bit\lib\httplib.pyc in _send_request(self, method, url, body, headers)
   1091         for hdr, value in headers.iteritems():
   1092             self.putheader(hdr, value)
-> 1093         self.endheaders(body)
   1094
   1095     def getresponse(self, buffering=False):

C:\arwa\Anaconda230-64bit\lib\httplib.pyc in endheaders(self, message_body)
   1047         else:
   1048             raise CannotSendHeader()
-> 1049         self._send_output(message_body)
   1050
   1051     def request(self, method, url, body=None, headers={}):

C:\arwa\Anaconda230-64bit\lib\httplib.pyc in _send_output(self, message_body)
    891             msg += message_body
    892             message_body = None
--> 893         self.send(msg)
    894         if message_body is not None:
    895             #message_body was not a string (i.e. it is a file) and

C:\arwa\Anaconda230-64bit\lib\httplib.pyc in send(self, data)
    853         if self.sock is None:
    854             if self.auto_open:
--> 855                 self.connect()
    856             else:
    857                 raise NotConnected()

C:\arwa\Anaconda230-64bit\lib\httplib.pyc in connect(self)
   1272
   1273             self.sock = self._context.wrap_socket(self.sock,
-> 1274                                                   server_hostname=server_hostname)
   1275
   1276     __all__.append("HTTPSConnection")

C:\arwa\Anaconda230-64bit\lib\ssl.pyc in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname)
    350                          suppress_ragged_eofs=suppress_ragged_eofs,
    351                          server_hostname=server_hostname,
--> 352                          _context=self)
    353
    354     def set_npn_protocols(self, npn_protocols):

C:\arwa\Anaconda230-64bit\lib\ssl.pyc in __init__(self, sock, keyfile, certfile, server_side, cert_reqs, ssl_version, ca_certs, do_handshake_on_connect, family, type, proto, fileno, suppress_ragged_eofs, npn_protocols, ciphers, server_hostname, _context)
    577                         # non-blocking
    578                         raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
--> 579                     self.do_handshake()
    580
    581             except (OSError, ValueError):

C:\arwa\Anaconda230-64bit\lib\ssl.pyc in do_handshake(self, block)
    806             if timeout == 0.0 and block:
    807                 self.settimeout(None)
--> 808             self._sslobj.do_handshake()
    809         finally:
    810             self.settimeout(timeout)

SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

Any idea of an additional dependency?
I will ask in the "gspread" issues as well.

**Comment by maybelinot** [comment]
### dependencies

All dependencies are listed in *setup.py* file:

    __irequires__ = [
	    # CORE DEPENDENCIES
	    'argparse==1.3.0',
	    'google-api-python-client==1.4.1',
	    'gspread==0.2.5',
	    'oauth2client>=1.4.12',
	    'pandas==0.16.2',
    ]

### oauth2 id creation problems

Something has changed, since I got credentials few months ago. Now my app has type "Other". So, try to continue instructions with this change.. And its seems reasonable for me to provide link to google instructions rather than check for any updates in Google API and then update readme.

I've made some changes, pull it and try to run it again

**Comment by maybelinot** [comment]
@spex66 Which version of gspread package do you have? For now I have no idea about missing dependencies, I will try to test it on windows too

**Comment by spex66** [comment]
Thx for the quick feedback.

gspread-0.2.5-py2.7 installed.

My Python is 2.7.10 64bit on Win10.

The issue with the SSL error seems to be already known:
==> https://github.com/burnash/gspread/pull/255

I'm in the process to isolate and reproduce the solution steps to fix the ```ssl.SSLContext``` based on the comments and pull request. No luck yet.

The SSL issue I run into seems to be triggered by this:
> but you can connect to a SSL backend and it will fail on all versions from 2.7.9 and 3.4 on up because of the changes made regarding PEP0476.

**Comment by spex66** [comment]
Only way to bypass the SSL error, was to path the gspread files:
* client.py
* httpsession.py
(using the exact one from the pull-request above)

But using a context ```None``` to rely on the default which is ```ssl.create_default_context()``` didn't changed it on Windows.

Because I'm at the moment not focused to solve the SSL issue, I've taken the shortcut which is an "unverified security context":
Before in gspread2df.py:
```
    # auth for gspread
    gc = gspread.authorize(credentials)
```
Patched in gspread2df.py (relying on a patched gspread):
```
    import ssl
    # auth for gspread
    gc = gspread.authorize(credentials, ssl._create_unverified_context())
```

Now it works :)
And I can proceed with testing the Pandas integration.

**Comment by kejbaly2** [comment]
Hey, thanks for the feedback! To be clear, have you managed to get df2gspread to work yet?

**Comment by spex66** [comment]
Hi @kejbaly2, yes.

* The first issues was fixed by @maybelinot (import of oauth2client)
* The Client Id Application type in the Google Developer Console dialog is confirmed working as  "other"
* the ```[SSL: CERTIFICATE_VERIFY_FAILED]``` error which happened with "gspread" can be fixed (better bypassed :)) through this mokeypatch.
Most likely this is related to Python >= 2.7.9 and the not working fallback to the default SSL context is maybe on Windows only:
```python
# monkeypatch https://www.python.org/dev/peps/pep-0476/
# https://github.com/abeloin/SickRage/commit/21fcea2c3155f57dba5c64a55f1f8fee02804256
import sys
if sys.version_info >= (2, 7, 9):
    import ssl
    ssl._create_default_https_context = ssl._create_unverified_context
```

FYI: Because I have a special use-case to download all worksheets from spreadsheet, with no column or row headers, I was able to optimize my script now to this.
(no idea if it makes sense to integrate it into this library, as a ```def download_all()``` option)

```python
# the oauth2 flow stays the same as in df2gspread/utils.py:get_credentials()

# the SSL context was patched above
gc = gspread.authorize(credentials)

# get spreadsheet
spsh = gc.open(GOOGLE_SHEET_NAME) # /Cxense - Amedia Ordlister/cxense-autotagging-dictionary'

# EXTRACT all worksheets
wkss = spsh.worksheets()
[wks.title for wks in wkss] # dump the titles

from collections import OrderedDict
dfs = OrderedDict()

# dump all sheets to DataFrames
_ = [dfs.update({wks.title : pd.DataFrame(wks.get_all_values())}) for wks in wkss]

# TRANSFORM and LOAD to another webservice
```

@maybelinot : Thank you so much, for the library... I was stuck there in April when Google has taken down the user/password authentication, and I never had the time to figure out the different approaches of the "Client Id Application" types.

**Comment by maybelinot** [comment]
@spex66 I'm glad to see that it helped you reach some of your goals. =)
