### ISSUE TITLE
Add flexibility in handling credentials

### ISSUE THREAD

**Issue by rothnic** [maybelinot/df2gspread#8]
I was trying to use this on a server and was having issues with the credentials. It might be useful to support either dependency injection of the google authentication object as an option, or directly support the --noauth_local_webserver option, and/or the service account credentials type.

I believe, at the moment, that the only way to authenticate with the current setup is by having a web browser to open the page up on the machine that is accessing the data.

**Comment by maybelinot** [comment]
I have reviewed #9 , did a couple of adjustments in  b79303b and merged it to master.

**Comment by RickyMcMaster** [comment]
Hi Eduard, I could only find the create_service_credentials() method in utils.py - am I right in saying that it also needs to be called from df2gspread.py and gspread2df.py?

Many thanks

**Comment by maybelinot** [comment]
@RickyMcMaster IIRC it needs to be used only if you want to create your credentials manually and then provide them to df2gspread or gspread2df as an optional parameter [here](https://github.com/maybelinot/df2gspread/blob/master/df2gspread/df2gspread.py#L40)

**Comment by RickyMcMaster** [comment]
But (and apologies if I am completely missing something very obvious), both df2gspread and gspread2df only import [get_credentials()](https://github.com/maybelinot/df2gspread/blob/b64036151b19cb05aa40eddd66e22d3d78546030/df2gspread/df2gspread.py#L17).

So I'm unable to see how you use service account credentials just by using  df2gspread or gspread2df in the existing code.
